services:
  example:
    image: tangl:1
    build: .
    volumes:
      - "$PWD/target/example:/home/tangl/example"
    command: bash -c "cd .. && tangl clone https://codeberg.org/tangl/construction-site-example.git && cd construction-site-example && tangl clone --track"